### ISSUE TITLE
Using Blink in codebase is not working 

### ISSUE THREAD

**Issue by pradeepharbour** [facebookresearch/BLINK#104]
Hi,

  As mentioned in the documentation, I have installed Blink with pip. But, when I try to import Blink in my codebase, it’s throwing module not found error.
   Is there anything I am missing apart from pip install?

Thanks in advance..

**Comment by pradeepharbour** [comment]
My bad ignore this, its working. I missed including -r in pip command

**Comment by Akshay0799** [comment]
I'm getting a module not found error for blink even when after installing all the packages from requirements.txt using pip.
