### ISSUE TITLE
Questions about fine-tuning

### ISSUE THREAD

**Issue by izuna385** [facebookresearch/BLINK#11]
In the original paper, for TAK-KBP 2010 dataset, 
> We use a subset of all Wikipedia linked mentions as our training data (A total of 9M examples)

My understanding is that fine-tuning for model which encodes both of the mention and entities are done like [Gillick et al., 2019](https://www.aclweb.org/anthology/K19-1049.pdf).

But [here](https://github.com/facebookresearch/BLINK/blob/master/blink/candidate_retrieval/README.md), it is written that fine-tuning was conducted under AIDA sets.

I can't find out, or am confusing about how fine-tuning was done. Particularly, in the point of datasets used.
If you'd know details of the training datasets for fine-tuning models, I'd appreciate it.
Thanks.

PS
Maybe I was mistaken.
In the original paper, it is written that BERT base is used for training.
Does this mean BERT base "architecture" for training? I mean, does the original paper say that 9M mentions were used for training BERT weights, which is to be evaluated for TACKBP datasets?
If so, by what means fine-tuning was conducted?

**Comment by fabiopetroni** [comment]
Hey @izuna385 , 

you are looking at the README of the old version of BLINK (now deprecated).
We didn't finetune BLINK on AIDA.
BLINK uses a BERT-base architecture and it's finetuned on 9M sampled wikipedia links.

**Comment by izuna385** [comment]
Thanks for rapid reply. I got it.
