### ISSUE TITLE
Understanding 'use BLINK in your codebase'

### ISSUE THREAD

**Issue by petulla** [facebookresearch/BLINK#12]
Hi this is exciting. I'm looking at the use in your codebase snippet. 

One question I had is about the `data_to_link` collection.

It appears the extracted entities are input to the model for link prediction. I'm wondering where this collection comes, if there is a helper script to generate it using NER or if this is designed to work with any NER library for contextual linking. I'm also using Flair so I could hook this code into an existing pipeline. If you have another script to format the data or extract entities that would be interesting to know about.

**Comment by ledw** [comment]
Hi @petulla, it is designed to work with any NER library. If you work with EL datasets, most of them already provide the mention boundary. You can check here to see how blink uses Flair to annotate examples: https://github.com/facebookresearch/BLINK/blob/master/blink/main_dense.py#L339

**Comment by petulla** [comment]
So it seems like I can use [this function](https://github.com/facebookresearch/BLINK/blob/master/blink/main_dense.py#L71-L92) to generate my own `data_to_link`, assuming Flair is loaded. It could be tweaked to the output of any other NER library.

The dictionary collection generated by `annotate()` could then be passed into `main_dense.run` with the `test_data` argument set to `data_to_link` to make predictions, right?

**Comment by ledw** [comment]
@petulla Yes that's right.

**Comment by petulla** [comment]
@ledw Sorry one other question. Is there code to train one's own knowledge base?

**Comment by petulla** [comment]
@ledw @fabiopetroni congratulations on KILT!! Still wondering if BYOKB will be possible; would be really useful for me to see the script for creating a BLINK kb from the raw KB.
