### ISSUE TITLE
Reproducing results on Zero Shot EL dataset from Logeshwaran Et al 

### ISSUE THREAD

**Issue by Srinivas-R** [facebookresearch/BLINK#13]
Hi! I was wondering if you have the code/model to quickly reproduce your results on the zero shot entity linking dataset by Logeshwaran et al as well, in addition to the benchmarks you've put up, or if there are plans to add that. Thank you!

**Comment by ledw** [comment]
Hi @Srinivas-R, yes we plan to update with the script to reproduce results on the zero-shot EL dataset soon.

**Comment by fgh95** [comment]
@ledw @fabiopetroni congratulations on this great work and thanks for sharing it! I was trying to re-train the Biencoder on a different dataset but it remains unclear to me how the zeshel dataset has been preprocessed and transformed into the .jsonl files that get used as an input for the Biencoder class. Are there any instructions or examples on the format of the train.jsonl and valid.jsonl files available? Thanks a lot!

**Comment by Eleni170** [comment]
Did you find a solution? @fgh95

**Comment by fgh95** [comment]
@Eleni170 I did not. I ended up implementing the Biencoder from scratch. Maybe this can be helpful: https://github.com/izuna385/Zero-Shot-Entity-Linking

**Comment by Eleni170** [comment]
@fgh95 I will take a look. Thank you very much.

**Comment by ledw** [comment]
Examples added here:
https://github.com/facebookresearch/BLINK/tree/master/examples/zeshel
