### ISSUE TITLE
Are entity IDs internal or do they match Wikidata or WIkipedia's Ids?

### ISSUE THREAD

**Issue by thepartisan101** [facebookresearch/BLINK#14]
Hi,

I'm considering this library for Entity linking, but within my application I need to find the corresponding Wikipedia URL.
Using your example, I tried Blink's Bert Id(97598) as Q97598 and pageid:97598 but I get completely different entities, so I'm wondering how I could get the KB id.

Wikidata results, using https://www.wikidata.org/w/api.php?action=wbgetentities&format=xml&props=sitelinks&ids=Q97598&sitefilter=frwiki
```
<api success="1">
<script/>
<entities>
<entity type="item" id="Q97598">
<sitelinks>
<sitelink site="frwiki" title="Else Quecke">
<badges/>
</sitelink>
</sitelinks>
</entity>
</entities>
</api>
```

Results as page ID using https://en.wikipedia.org/w/api.php?action=query&prop=info&pageids=97598&inprop=url
```
{
    "batchcomplete": "",
    "query": {
        "pages": {
            "97598": {
                "pageid": 97598,
                "ns": 1,
                "title": "Talk:Geneva County, Alabama",
                "contentmodel": "wikitext",
                "pagelanguage": "en",
                "pagelanguagehtmlcode": "en",
                "pagelanguagedir": "ltr",
                "touched": "2020-05-05T21:27:47Z",
                "lastrevid": 805052689,
                "length": 3123,
                "fullurl": "https://en.wikipedia.org/wiki/Talk:Geneva_County,_Alabama",
                "editurl": "https://en.wikipedia.org/w/index.php?title=Talk:Geneva_County,_Alabama&action=edit",
                "canonicalurl": "https://en.wikipedia.org/wiki/Talk:Geneva_County,_Alabama"
            }
        }
    }
}
```

Thanks for any help on this

**Comment by ledw** [comment]
@thepartisan101 Thanks for considering using the library. In the interactive mode, you can pass --show_url to show the url of wikipedia entity. 
The displayed id is in corresponding to the row number in entity.jsonl file (downloaded from the download_models.sh script). Note id starts from 0. You can find more information in the entity.jsonl file, including the entity title, text, wikipedia url, etc.

**Comment by ledw** [comment]
Updated README to include information above.
