### ISSUE TITLE
Will you be releasing the knowledge base training script?

### ISSUE THREAD

**Issue by petulla** [facebookresearch/BLINK#15]
Hi

This is exciting. There's a chance we'll use it at CNN. I'm interested in the knowledge base training, however. We'd want to be able to retrain on occasion, even if it takes a few weeks on 8 gpus as you mentioned. Can you provide more insight into whether you'll open those scripts?

**Comment by ledw** [comment]
@petulla Yes, we plan to update with instructions on how to train the model as well.

**Comment by petulla** [comment]
Cool, just for my sake, is that something you estimate you'll release in 1 week, 1 month or 1 year in terms of order of magnitude?

**Comment by ledw** [comment]
@petulla We should be able to update that in the next couple of weeks.
