### ISSUE TITLE
Question about the training of Section 5.2.2 TACKBP datasets

### ISSUE THREAD

**Issue by izuna385** [facebookresearch/BLINK#16]
I am still very interested in your paper and would like to ask you a question.

Is the BERT used for the TACKBP dataset pre-trained in advance? The paper doesn't seem to make this explicit. 
That is, as well as "5.2.1 Zero-shot Entity Linking", did you finetune the pretrained BERT and train Bi-encoder at the same time? If so, was in-batch negative sampling used for training, like [Gillick et al., '19] or [Humeau et al., '20] ? (And then re-finetune with the top100 retreived candidates?)

The summary is that I'm confusing about the sentence in Sec 5.2.2. 

> we pre-train our models on Wikipedia data

Does this mean you trained BERT from scratch, or used pretrained BERT and trained bi-encoder (, which leads to fine-tune BERT weights during the training of bi-encoder)?

If you'd know about this, I'd appreciate it.

**Comment by ledw** [comment]
@izuna385 Thanks for the questions. The BERT models are pre-trained on Wikipedia. In Sec 5.2.2, we meant that we also use wikipedia to train our bi-encoder model, initialized from pre-trained BERT models. We'll make that point clear in future versions of the paper.

**Comment by izuna385** [comment]
Looking forward to the next update. Thanks for kind clarification!
