### ISSUE TITLE
ModuleNotFoundError: No module named 'blink'

### ISSUE THREAD

**Issue by AmoghM** [facebookresearch/BLINK#18]
When I run `python blink/main_dense.py -i`
I am getting an error which I am unable to fix.
`Traceback (most recent call last):
  File "blink/main_dense.py", line 6, in <module>
    import blink.ner as NER
ModuleNotFoundError: No module named 'blink'`

My sys.path returns a list which contains `<rest-of-the-path>\BLINK\\blink`. Please help.

**Comment by petulla** [comment]
I have had this same issue..

**Comment by Meghana-Meghana** [comment]
The main_dense.py is inside the blink folder same as ner.py (which is being imported) . Hence, running `python blink/main_dense.py -i` will give the `ModuleNotFoundError`. However, if you move the main_dense.py to outside of blink folder and run `python main_dense.py -i`, you will not get that error.

**Comment by ledw** [comment]
@AmoghM @petulla : have you tried this? https://github.com/facebookresearch/BLINK#troubleshooting

**Comment by petulla** [comment]
@ledw I'm trying to use in a codebase as a module. Am trying that fix in that context now.. no luck yet.

**Comment by AmoghM** [comment]
Still the same issue

**Comment by AmoghM** [comment]
Thanks, @ledw and @Meghana-Meghana. Both of your tricks worked. @Meghana-Meghana would be recommended for someone who wants to run it on Windows but don't wanna set it as an Environment variable. The exact command for troubleshooting I used was: <br> ` PYTHONPATH=. python blink/main_dense.py`. Might be helpful for someone in future.
