### ISSUE TITLE
Error in generating candidate encodings for custom KB with eval_biencoder.py

### ISSUE THREAD

**Issue by ankushkundaliya** [facebookresearch/BLINK#29]
I'm trying to generate and store candidate encoding for a custom KB. For this I am using eval_biencoder.py script.

I have found two issues in the eval_biencoder.py :
1. Typo at line #42 "degug" instead of "debug" is passed to params.
2. main() is directly calling encode_candidate_zeshel() for generating candidate encoding without checking candidate_pool type.  candidate_pool for non zeshel is not a dictionary but list and hence throughs error at line #131.

![image](https://user-images.githubusercontent.com/26478051/88387457-17897f00-cdd0-11ea-804d-f2e579bb4868.png)

**Comment by fabiopetroni** [comment]
Thanks a lot for taking the lead and fixing those :)
