### ISSUE TITLE
SolrError while running data_ingestion.py

### ISSUE THREAD

**Issue by shmsw25** [facebookresearch/BLINK#3]
Hi, thanks for open-sourcing this framework. I got an error while running `blink/candidate_retrieval/data_ingestion.py` for preprocessing. It gives `SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]` when the data is added in solr (`solr.add(temp_data, commit=True)`). I checked if solr is not running properly, but since `bin/solr status` gives `Solr process 49321 running on port 8983`, it seems to be running properly. Is there any possible reason that causes the error? Thank you!

**Comment by ledw** [comment]
Hi @shmsw25, sorry for not responding earlier. We decided to remove the solr dependency in the new version. Please checkout the newest version if you're still interested to try out BLINK. Thanks!
