### ISSUE TITLE
ZeroDivisionError: float division by zero Error

### ISSUE THREAD

**Issue by rishabhjoshi** [facebookresearch/BLINK#34]
Hi, I set up the environment for interactive testing BLINK.
When I run any of these commands:
```
PYTHONPATH=. python blink/main_dense.py -i
PYTHONPATH=. python blink/main_dense.py -i --faiss_index hnsw --index_path models/faiss_hnsw_index.pkl
PYTHONPATH=. python blink/main_dense.py -i --faiss_index flat --index_path models/faiss_flat_index.pkl
```
and enter the text as : "federer plays tennis", I get the following error:
```
insert text:federer plays tennis

federer plays tennis

2020-08-17 23:45:57,810 preparing data for biencoder
2020-08-17 23:45:57,811 run biencoder
0it [00:00, ?it/s]

fast (biencoder) predictions:

federer plays tennis


0it [00:00, ?it/s]
Evaluation: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "blink/main_dense.py", line 680, in <module>
    run(args, logger, *models)
  File "blink/main_dense.py", line 506, in run
    context_len=biencoder_params["max_context_length"],
  File "blink/main_dense.py", line 276, in _run_crossencoder
    res = evaluate(crossencoder, dataloader, device, logger, context_len, silent=False)
  File "<BLINKPATH>/BLINK/blink/crossencoder/train_cross.py", line 95, in evaluate
    normalized_eval_accuracy = eval_accuracy / nb_eval_examples
ZeroDivisionError: float division by zero
```

However, if I run this command:
```
PYTHONPATH=. python blink/main_dense.py -i --fast
```
it works perfectly (not able to link "federer" though, but doesn't crash with the error).

Also,
For the first set of commands above, if I write "roger federer plays tennis", it works and is able to link roger federer. However, if I write any text (for eg: i like to play tennis), it crashes with the same ZeroDivisionError. I guess it is not able to handle cases when it is not able to find any match. Surprisingly it works for the --fast case.

**Comment by ledw** [comment]
@rishabhjoshi Thanks for reporting. The zero-division error is fixed. If you change the input to "Federer plays tennis", it identifies "Federer". This is a known issue for the NER component.
