### ISSUE TITLE
Solr error while querying

### ISSUE THREAD

**Issue by karinseve** [facebookresearch/BLINK#4]
I am trying to generate the candidates from step 2 with:

    python blink/candidate_retrieval/perform_and_evaluate_candidate_retrieval_multithreaded.py \
    --num_threads 70 \
    --dump_mentions \
    --dump_file_id train_and_eval_data \
    --include_aida_train

However, while querying the collection, Solr gives an exception:

    SolrError("Failed to connect to server at ... Failed to establish a new connection: [Errno 111] 
    Connection  refused',))",)

More specifically, the exception occurs in file `candidate_generators.py`, on line 85:

    results = solr.search(query, **self.query_arguments)

If I check the GUI and run the queries there, it works fine.
What could possibly go wrong? Solr seems to be running fine as well.

Thanks!

**Comment by ledw** [comment]
Hi @karinseve, sorry for not responding earlier. We decided to remove the solr dependency in the new version. Please checkout the newest version if you're still interested to try out BLINK. Thanks!
