### ISSUE TITLE
Saving candidate encoding fails in BiEncoder

### ISSUE THREAD

**Issue by HelloRusk** [facebookresearch/BLINK#50]
I found the code below is not working.

https://github.com/facebookresearch/BLINK/blob/f0962a0eccff553c82c8cbbb3f456cf7f2c7acce/blink/biencoder/eval_biencoder.py#L251-L254

Maybe the arguments are left and right reversed.

```py
torch.save(candidate_encoding, cand_encode_path) 
```

**Comment by ledw** [comment]
Thanks for reporting. It's fixed in https://github.com/facebookresearch/BLINK/commit/3ffd7febf84b0b749dd4685b1af0342717e5a4ac.
