### ISSUE TITLE
Benchmark Results

### ISSUE THREAD

**Issue by mehrdad-naser-73** [facebookresearch/BLINK#51]
Hi,

I would like to ask a question regarding the benchmark results on widely used EL datasets like AIDA-YAGO and msnbc. I noticed that the reported accuracies are much lower than older non-transformer-based models which is surprising considering the high recall@100. Is this purely due to not fine-tuning on the training set of those datasets?

**Comment by ledw** [comment]
@mehrdad-naser-73 Hi, thanks for the questions. Yes it is largely due to not fine-tuning on the training set. We have numbers comparable when we fine-tune on the datasets.

**Comment by mehrdad-naser-73** [comment]
Thanks for the clarification.
