### ISSUE TITLE
use own NER results

### ISSUE THREAD

**Issue by yuchenlin** [facebookresearch/BLINK#52]
Hi thanks for the amazing tool.

We are wondering if it would be possible that we could specify our own NER results (i.e., span of mentions) instead of using flair's. 

Thanks!

**Comment by ledw** [comment]
Hi @yuchenlin, yes you can use your own NER results. Check the example on the README on how to use BLINK in your code: 
https://github.com/facebookresearch/BLINK#4-use-blink-in-your-codebase
Basically specifying the following fields:
```
{
    "context_left": "".lower(),
    "mention": "Shakespeare".lower(),
    "context_right": "'s account of the Roman general Julius Caesar's murder by his friend Brutus is a meditation on duty.".lower(),
}
```
where "mention" contains the mention detected by your NER system, and "context_left", "context_right" is the context around it.

**Comment by yuchenlin** [comment]
Thanks! We found that and now are using this method. We wonder if it is possible to also specify the entity type to make the prediction more accurate. For example, we found that the "XXXX,  Hong Kong 's YYYY", the mention HK's will be linked to HK airport (FAC) instead of the HK city (GPE), because the YYY mentions airport-related context.  Thank you very much!

**Comment by abhinavkulkarni** [comment]
@yuchenlin: Ideally the context should help the model disambiguate HK, the airport from HK, the city. After all, the NER model also uses more or less the same context to predict entity type, so it is reasonable to assume that that knowledge is folded into biencoder model.
