### ISSUE TITLE
No module named 'XXXXXX'

### ISSUE THREAD

**Issue by Grace-Wang-Lab** [facebookresearch/BLINK#58]
#    Executing python under linux prompts module not found，E.g：_from blink.indexer.faiss_indexer import DenseFlatIndexer, DenseHNSWFlatIndexer_   --->>>No module named 'blink'

**Comment by HelloRusk** [comment]
Hello.
This issue might be related --> #18 
I also came across the error `No module named 'blink'` once, and fixed it by moving the python file.
Prefixing `PYTHONPATH=.` is an alternative idea.

**Comment by Grace-Wang-Lab** [comment]
@HelloRusk OK，Thank you very much.
