### ISSUE TITLE
What is the difference between cand_encode_path and cand_pool_path in Biencoder?

### ISSUE THREAD

**Issue by HelloRusk** [facebookresearch/BLINK#68]
There are two similar parameters named `cand_encode_path` and `cand_pool_path`. How do they differ?

https://github.com/facebookresearch/BLINK/blob/master/blink/biencoder/eval_biencoder.py#L217-L237

**Comment by HelloRusk** [comment]
I'm not sure but I can grasp a little now ...

- `cand_pool_path` is the cached data of converted tokens 
- `cand_encode_path` is the cached data of converted vectors

🤔

**Comment by ledw** [comment]
Hi @HelloRusk , thanks for your question. Yes your guess is correct.

**Comment by ledw** [comment]
Updated parameter explanation: https://github.com/facebookresearch/BLINK/commit/3aa75aef040af3d8f7c85a10d320474bd71283e2
Please let us know if there's any other question.
