### ISSUE TITLE
Results under bert-base model

### ISSUE THREAD

**Issue by leezythu** [facebookresearch/BLINK#73]
Hi, I am very interested in this work and reproducing the results, but I have to use bert-base model instead of the large one due to my limited resources. 
Have you trained and tested BLINK(bert-base) on  TACKBP-2010 and WikilinksNED Unseen-Mentions datasets? If so, could you please tell me the accuracy results on these two datasets to check my reproducing results ? (for example on WikilinksNED Unseen-Mentions , the 'Wiki (bi-encoder)' acc , the 'Wiki and in-domain' acc etc. )
Thank you!

**Comment by abhinavkulkarni** [comment]
@leezythu: I have trained a smaller model on my custom dataset, so it is indeed possible to train a smaller model. I would recommend first training a zeshel model using your choice of bert-base, then bring your data in the same format as zeshel.

Scripts to download and pre-process zeshel data set are in the repository.

**Comment by leezythu** [comment]
@abhinavkulkarni Thank you! It helps a lot.
