### ISSUE TITLE
'KeyedVectors' object has no attribute 'key_to_index'

### ISSUE THREAD

**Issue by wutaiqiang** [facebookresearch/BLINK#81]
When i am runing the code, this error occurs after i input the text as interrace mode:
>'KeyedVectors' object has no attribute 'key_to_index'

this is because the gensim version is not suitable for flair

ref: https://github.com/flairNLP/flair/issues/2196

**Comment by wutaiqiang** [comment]
@likethesky Maybe you can add this version requirement in the requirements.txt file

**Comment by f-guitart** [comment]
I solved it using gensim==3.5.0

**Comment by wutaiqiang** [comment]
Low version of gensim may work well
